### ISSUE TITLE
Unable to open SD card

### ISSUE THREAD

**Issue by RA-NGR** [EremusOne/ZX-ESPectrum-IDF#52]
![SD-Fail](https://github.com/EremusOne/ESPectrum/assets/28787099/6ce5d155-b2a9-4e35-ae74-ae95d4d63876)
Module: TTGO VGA32 
ESPectrum version: 1.2
I made simple SD card test scketch
![SD-Check](https://github.com/EremusOne/ESPectrum/assets/28787099/fef273c8-ce65-4a97-8e70-3ad50fe1439c)

**Comment by Gods69** [comment]
No problems here. Have you tried another brand of SD card?

**Comment by EremusOne** [comment]
Hi @RA-NGR !

SD card is working flawlessly for everyone in all the boards tested with ESPectrum 1.2 so please give me some context about your issue:

- Exact model of Lilygo board (v1.2 or v1.4).
- How do you installed ESPectrum in the board: flashed with Espressif tool or built through repo code+VSCode + PlatformIO.
- Format of the card you are using.

Also, some video of the problem will be helpful.

Regards ;)

**Comment by RA-NGR** [comment]
Hi @EremusOne 
The board is v1.4
ESPectrum.1.2.bin flashed with Espressif tool (I tried flash v1.1 - SD not working)
I tried both FAT and FAT32
Video is preparing, give me a couple of days

Hi @Gods69 
The card fully working with my test sketch (I take it from Arduino SD card example and slightly modify). So problem isn't brand

**Comment by Gods69** [comment]
I also have the TTGO VGA32 v1.4 with no problems. 
I'm using a old 1GB Sandisk SD card and updated to FW 1.2 via "SD card update" method.

**Comment by RA-NGR** [comment]
Hi. Victor.
Here  http://www.atpilot.ru/IMG_4584.MOV is the video, but I think it is not helpful

**Comment by Gods69** [comment]
Hi,
You need to try another memory card. There are several ways to access an SD card via software and your card (512MB) may not support the way it is accessed. (Also try to format it in FAT32)

**Comment by RA-NGR** [comment]
> Hi,
> 
> You need to try another memory card. There are several ways to access an SD card via software and your card (512MB) may not support the way it is accessed. (Also try to format it in FAT32)

Ok, I will try. But card also working good in my "spectrum" based on rp2040 ![image](https://github.com/EremusOne/ESPectrum/assets/28787099/44a489ee-d08f-4abf-a927-918c5c01a6f3)

**Comment by EremusOne** [comment]
Hi @RA-NGR 

There are potential incompatibilities between SD card readers and various brands or types of cards. In its current state, ESPectrum, on the Lilygo TTGO VGA32 v1.4, has proven to be very reliable, and most users who have encountered problems have resolved them by properly reformatting or changing the card.

In any case, I do not rule out the possibility that the malfunction could be corrected via software and that it might be possible to get that stubborn card to work. Unfortunately, I cannot dedicate time to this right now, and I would also need your card to test different settings because I don't have any faulty card (I've never had any problem with all the cards I've tested).

So, my advice is to test with a different and, if possible, newer and of a known and reliable brand (I use Sandisk Ultra 32gb and 64gb with excellent results).

One question: ¿That sketch you posted first was executed on the same Lilygo where ESPectrum doesn't read your card or in different hardware?

Regards

**Comment by RA-NGR** [comment]
Hi, Victor.
The sketch executed on the same board and it's really strangely.
So I opened issue.
Ok, I will try another card, thank you.
You may close this issue
